### ISSUE TITLE
Hi there is a complie error to build

### ISSUE THREAD

**Issue by jongminjeong** [RobDickinson/pmemkv-tools#17]
Hi there is a complie error to build.. i see pmemkv_config_put_string was not declared in this scope and pmemkv_config_put_uint64 is same and no matching function for call to db
kv_ = new pmem::kv::db;

**Comment by vinser52** [comment]
@jongminjeong Please make sure you are using the latest version of pmemkv.

**Comment by lukaszstolarczuk** [comment]
It seems there's no problem anymore. Closing for now. If you fell like you need any more assistance, don't hesitate to re-open this issue.
