### ISSUE TITLE
No difference between readmissing and readrandom

### ISSUE THREAD

**Issue by abhineet99** [RobDickinson/pmemkv-tools#32]
Looking at the current code, I couldn't find any difference between readmissing and readrandom benchmarks. 
I suppose readmissing is intended to try to read key-value pairs which do not exist in database.
Let me know if I've misunderstood what readmissing is supposed to do, or if I've missed anything in the code.

**Comment by igchor** [comment]
Yes, I believe you're right. There should be some additional character inserted to the key in case if `missing` flag is specified in `DoRead` (to make sure it does not compare equal to any of the existing ones).

Any contribution is welcome :)

**Comment by igchor** [comment]
Solved in #34
